---
#


- name: install dotfiles
  git:
    repo: "https://github.com/davidfic/dotfiles.git"
    dest: /Users/dficociello/tmp


- name: pip install needed packages
  pip: 
    name: "{{ name }}"
  with_items:
    - virtualenv
    - virtualenvwrapper
    - requests